### ISSUE TITLE
Tests to build schema, lint schema, and install chart in k8s without crashing

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/binderhub-service#4]
This involves ensuring the [.github/workflows/test-chart.yaml](https://github.com/2i2c-org/binderhub-service/blob/main/.github/workflows/release.yaml) triggers and runs correctly, installing the helm chart and the started pods startup correctly without crashing.

---

Note that this is part of a https://github.com/2i2c-org/binderhub-service/milestone/1 with a time estimate.

**Comment by consideRatio** [comment]
Not yet a success:

```
### $ kubectl logs --all-containers deploy/binderhub-service
[W 230324 13:03:08 app:680] Generating random build token secret. Set BinderHub.build_token_secret to avoid this warning.
[I 230324 13:03:08 app:1035] BinderHub starting on port 8585
[E 230324 13:03:08 app:1031] Failed to cleanup builders
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/binderhub/app.py", line 1029, in watch_builders
        await asyncio.wrap_future(self.executor.submit(cleaner.cleanup))
      File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/binderhub/build.py", line 642, in cleanup
        builds = self.kube.list_namespaced_pod(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 15697, in list_namespaced_pod
        return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 15[81](https://github.com/2i2c-org/binderhub-service/actions/runs/4511444623/jobs/7943598268#step:11:84)2, in list_namespaced_pod_with_http_info
        return self.api_client.call_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
        return self.__call_api(resource_path, method,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
        response_data = self.request(
                        ^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
        return self.rest_client.GET(url,
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 241, in GET
        return self.request("GET", url,
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 235, in request
        raise ApiException(http_resp=r)
    kubernetes.client.exceptions.ApiException: (403)
    Reason: Forbidden
    HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e51c3150-aa54-46ee-ac3f-56ff9ac13f6a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '711125d8-bc8f-4fa7-8f4a-087ad9210ae0', 'X-Kubernetes-Pf-Prioritylevel-Uid': '[84](https://github.com/2i2c-org/binderhub-service/actions/runs/4511444623/jobs/7943598268#step:11:87)0740df-d393-402c-9e08-b8b4d[87](https://github.com/2i2c-org/binderhub-service/actions/runs/4511444623/jobs/7943598268#step:11:90)12f4c', 'Date': 'Fri, 24 Mar 2023 13:03:08 GMT', 'Content-Length': '2[92](https://github.com/2i2c-org/binderhub-service/actions/runs/4511444623/jobs/7943598268#step:11:95)'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:default:binderhub-service\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```
